# -*- coding: utf-8 -*-
"""transformando_imagens_binarizacao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f5zbUPXAZTBZ4zGN4c6MpmAz-9njLIQW
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

imagem = cv2.imread('/content/minha_imagem.jpg')

altura, largura, _ = imagem.shape

# Inicializando
cinza = np.zeros((altura, largura), dtype=np.uint8)
binaria = np.zeros((altura, largura), dtype=np.uint8)

# Convertendo manualmente para cinza
for i in range(altura):
    for j in range(largura):
        b, g, r = imagem[i, j]
        cinza[i, j] = int((int(r) + int(g) + int(b)) / 3)


limiar = 127
binaria[cinza >= limiar] = 255

# Converter para RGB
imagem_rgb = cv2.cvtColor(imagem, cv2.COLOR_BGR2RGB)

# Mostrar imagens e histograma
plt.figure(figsize=(18, 5))

plt.subplot(1, 4, 1)
plt.imshow(imagem_rgb)
plt.title('Colorida')
plt.axis('off')

plt.subplot(1, 4, 2)
plt.imshow(cinza, cmap='gray')
plt.title('Tons de Cinza')
plt.axis('off')

plt.subplot(1, 4, 3)
plt.imshow(binaria, cmap='gray')
plt.title(f'Binária\n(limiar={limiar})')
plt.axis('off')
plt.grid(True)

plt.tight_layout()
plt.show()